export const FETCH_TODOS_SUCCESS = "FETCH_TODOS_SUCCESS"; 
export const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS";
export const TOGGLE_TODO_SUCCESS = "TOGGLE_TODO_SUCCESS";
export const DELETE_TODO_SUCCESS = "DELETE_TODO_SUCCESS";
export const SET_FILTER = "SET_FILTER";